"""init add request path column

Revision ID: 772313f9591c
Revises: bffec43c37ae
Create Date: 2024-01-15 14:42:00.520657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772313f9591c'
down_revision: Union[str, None] = 'bffec43c37ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('request_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'request_path')
    # ### end Alembic commands ###
